apiVersion: v1
kind: Service #define the object
metadata:
  name: nginx-app-loadbalancer
spec:
  type: LoadBalancer # We want LB, ClusterIP or NodePort
  selector: # IMPORTANT THIS IS WHERE THE MAGIC HAPPENS!!!
    app: nginx # hey load balance accros any pod with tag app=nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # backend port