apiVersion: apps/v1  # Required and depends on the object
kind: Deployment # Deployment object
metadata:  # Describe the object or infra
  name: nginx-app-deployment #wtr
  labels: #tag
    app: nginx
spec:
  replicas: 2 # Kinda autoscaling for pods REPLICASET OBJECT
  selector:
    matchLabels: # use to tag as a match maker
      app: nginx
  template: # create a template for all the pod to be created
    metadata:
      labels:
        app: nginx # allnew pods will be tagged with this label
    spec: # containers inside the pods
      containers: #define a list of containers!!!!
      - name: nginx-container
        image: nginx:1.21
        ports:
        - containerPort: 80 # port it will listen inside the container
